version: "3.9"

services:
 eurekaserver:
   build: /Users/aymenbouthour/Downloads/EurekaServer
   container_name: eureka
   image: eureka
   networks:
      - eureka-server
   ports:
    - "8761:8761"

 microservice-demo:
   build: /Users/aymenbouthour/Downloads/gestion-candidat
  #  network_mode: host 
   image: gestioncondidat
   ports:
   - "5600:5600"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

networks:
  eureka-server:
    name: eureka-server
    driver: bridge
